runtime: python37
service: calculator
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 3